name: Sanity and Static Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - '**'
  push:
    branches:
      - '**'

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  sanity-check:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code with full history
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2️⃣ Detect language
      - name: Detect language
        id: detect
        run: |
          echo "Detecting languages changed in PR..."
          FILES=$(git diff --name-only HEAD~1 HEAD)
          echo "Files changed:"
          echo "$FILES"

          if echo "$FILES" | grep -qE '\.js$|\.jsx$'; then
            echo "language=js" >> $GITHUB_OUTPUT
          elif echo "$FILES" | grep -qE '\.c$|\.cpp$'; then
            echo "language=cpp" >> $GITHUB_OUTPUT
          elif echo "$FILES" | grep -qE '\.java$'; then
            echo "language=java" >> $GITHUB_OUTPUT
          elif echo "$FILES" | grep -qE '\.kt$'; then
            echo "language=kotlin" >> $GITHUB_OUTPUT
          elif echo "$FILES" | grep -qE '\.swift$'; then
            echo "language=swift" >> $GITHUB_OUTPUT
          elif echo "$FILES" | grep -qE '\.rs$'; then
            echo "language=rust" >> $GITHUB_OUTPUT
          elif echo "$FILES" | grep -qE '\.dart$'; then
            echo "language=dart" >> $GITHUB_OUTPUT
          else
            echo "language=unknown" >> $GITHUB_OUTPUT
          fi

          echo "Detected language: $LANGS"

      # 3️⃣ Setup Node.js for JS
      - name: Setup Node.js (for JS)
        if: steps.detect.outputs.language == 'js'
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 4️⃣ Run ESLint for JS
      - name: Run ESLint
        if: steps.detect.outputs.language == 'js'
        run: |
          npm install -g eslint
          npx eslint sample-code/js

      # 5️⃣ Comment on success
      - name: Comment on PR success
        if: success() && github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            ✅ Sanity Check Completed for **${{ steps.detect.outputs.language }}**
            - Branch: `${{ github.head_ref || github.ref_name }}`
            - All checks passed.

      # 6️⃣ Add label for passing PRs
      - name: Add label on success
        if: success() && github.event_name == 'pull_request'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: Sanity Check

      # 7️⃣ Comment on failure
      - name: Comment on failure
        if: failure() && github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            ❌ Sanity Check **FAILED** for **${{ steps.detect.outputs.language }}**
            - Branch: `${{ github.head_ref || github.ref_name }}`
            - Please fix linting or code issues before merging.
