name: Sanity and Static Check

on:
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
    sanity-check:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Detect language
              id: detect
              run: |
                  echo "Detecting language..."
                  LANGS=$(git diff --name-only origin/main...HEAD | awk -F. '{print $NF}' | sort -u)
                  echo "Languages found: $LANGS"
                  if echo "$LANGS" | grep -q "js"; then
                    echo "language=js" >> $GITHUB_OUTPUT
                  else
                    echo "language=unknown" >> $GITHUB_OUTPUT
                  fi

            - name: Setup Node.js (for JavaScript check)
              if: steps.detect.outputs.language == 'js'
              uses: actions/setup-node@v4
              with:
                  node-version: '18'

            - name: Run ESLint
              if: steps.detect.outputs.language == 'js'
              run: |
                  npm install -g eslint
                  npx eslint sample-code/js || echo "No lint errors found."

            - name: Comment on PR
              uses: marocchino/sticky-pull-request-comment@v2
              with:
                  message: |
                      ✅ Sanity Check Completed for **${{ steps.detect.outputs.language }}**

            - name: Add label
              uses: actions-ecosystem/action-add-labels@v1
              with:
                  labels: Sanity Check
